FROM n8nio/n8n:latest

USER root

RUN mkdir -p /home/node/scripts

COPY scripts/ /home/node/scripts/

RUN chown -R node:node /home/node/scripts && \
    chmod -R 755 /home/node/scripts

USER node

EXPOSE 5678
CMD ["sh", "-c", "N8N_PORT=${PORT:-5678} N8N_LISTEN_ADDRESS=0.0.0.0 n8n start"]

